theme: jekyll-theme-minimal
title: Flavien Chamay
description: This is my Markdown online CV hosted in GitHub for future employers
logo: https://avatars.githubusercontent.com/u/45509747?s=400&u=515203f2e9c942b179befc85d3c5533ef6a05b98&v=4
show_downloads: true
